{"publishedDate": "2021-12-14T15:15Z", "lastModifiedDate": "2024-11-21T06:36Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2021-4007", "ASSIGNER": "cve@rapid7.com"}, "description": {"description_data": [{"lang": "en", "value": "Rapid7 Insight Agent, versions 3.0.1 to 3.1.2.34, suffer from a local privilege escalation due to an uncontrolled DLL search path. Specifically, when Insight Agent versions 3.0.1 to 3.1.2.34 start, the Python interpreter attempts to load python3.dll at \"C:\\DLLs\\python3.dll,\" which normally is writable by locally authenticated users. Because of this, a malicious local user could use Insight Agent's startup conditions to elevate to SYSTEM privileges. This issue was fixed in Rapid7 Insight Agent 3.1.2.35. This vulnerability is a regression of CVE-2019-5629."}, {"lang": "es", "value": "Rapid7 Insight Agent, versiones 3.0.1 a 3.1.2.34, sufre una escalada de privilegios local debido a una ruta de b\u00fasqueda de DLL no controlada. En concreto, cuando se inician las versiones 3.0.1 a 3.1.2.34 del Agente Insight, el int\u00e9rprete de Python intenta cargar python3.dll en \"C:\\DLLs\\python3.dll\", que normalmente es escribible por los usuarios autenticados localmente. Debido a esto, un usuario local malicioso podr\u00eda usar las condiciones de inicio del Agente Insight para elevarse a privilegios SYSTEM. Este problema ha sido corregido en Rapid7 Insight Agent versi\u00f3n 3.1.2.35. Esta vulnerabilidad es una regresi\u00f3n de CVE-2019-5629"}]}, "references": {"reference_data": [{"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=2019-5629", "name": "", "refsource": "", "tags": ["Third Party Advisory"]}, {"url": "https://docs.rapid7.com/release-notes/insightagent/20211210/", "name": "", "refsource": "", "tags": ["Release Notes", "Third Party Advisory"]}, {"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=2019-5629", "name": "", "refsource": "", "tags": ["Third Party Advisory"]}, {"url": "https://docs.rapid7.com/release-notes/insightagent/20211210/", "name": "", "refsource": "", "tags": ["Release Notes", "Third Party Advisory"]}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-427"}]}]}}, "impact": {"baseMetricV2": {"cvssV2": {"version": "2.0", "vectorString": "AV:L/AC:L/Au:N/C:C/I:C/A:C", "baseScore": 7.2, "accessVector": "LOCAL", "accessComplexity": "LOW", "authentication": "NONE", "confidentialityImpact": "COMPLETE", "integrityImpact": "COMPLETE", "availabilityImpact": "COMPLETE"}, "exploitabilityScore": 3.9, "impactScore": 10.0, "severity": "HIGH", "obtainAllPrivilege": false, "obtainUserPrivilege": false, "obtainOtherPrivilege": false, "userInteractionRequired": false}, "baseMetricV3": {"exploitabilityScore": 1.8, "impactScore": 5.9, "cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H", "baseScore": 7.8, "baseSeverity": "HIGH", "attackVector": "LOCAL", "attackComplexity": "LOW", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "HIGH"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "negate": false, "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:rapid7:insight_agent:*:*:*:*:*:*:*:*", "matchCriteriaId": "3572C5C5-7D73-4780-A92E-88AC1238F9C9", "cpe_name": [], "versionStartIncluding": "3.0.1", "versionEndExcluding": "3.1.2.35"}]}]}}