{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2024-38582", "ASSIGNER": "cve@kernel.org"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://git.kernel.org/stable/c/06afce714d87c7cd1dcfccbcd800c5c5d2cf1cfd", "name": "https://git.kernel.org/stable/c/06afce714d87c7cd1dcfccbcd800c5c5d2cf1cfd", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/06afce714d87c7cd1dcfccbcd800c5c5d2cf1cfd", "name": "https://git.kernel.org/stable/c/06afce714d87c7cd1dcfccbcd800c5c5d2cf1cfd", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/1c3844c5f4eac043954ebf6403fa9fd1f0e9c1c0", "name": "https://git.kernel.org/stable/c/1c3844c5f4eac043954ebf6403fa9fd1f0e9c1c0", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/1c3844c5f4eac043954ebf6403fa9fd1f0e9c1c0", "name": "https://git.kernel.org/stable/c/1c3844c5f4eac043954ebf6403fa9fd1f0e9c1c0", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/6e5c8e8e024e147b834f56f2115aad241433679b", "name": "https://git.kernel.org/stable/c/6e5c8e8e024e147b834f56f2115aad241433679b", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/6e5c8e8e024e147b834f56f2115aad241433679b", "name": "https://git.kernel.org/stable/c/6e5c8e8e024e147b834f56f2115aad241433679b", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/911d38be151921a5d152bb55e81fd752384c6830", "name": "https://git.kernel.org/stable/c/911d38be151921a5d152bb55e81fd752384c6830", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/911d38be151921a5d152bb55e81fd752384c6830", "name": "https://git.kernel.org/stable/c/911d38be151921a5d152bb55e81fd752384c6830", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/a8799662fed1f8747edae87a1937549288baca6a", "name": "https://git.kernel.org/stable/c/a8799662fed1f8747edae87a1937549288baca6a", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/a8799662fed1f8747edae87a1937549288baca6a", "name": "https://git.kernel.org/stable/c/a8799662fed1f8747edae87a1937549288baca6a", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/bc9cee50a4a4ca23bdc49f75ea8242d8a2193b3b", "name": "https://git.kernel.org/stable/c/bc9cee50a4a4ca23bdc49f75ea8242d8a2193b3b", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/bc9cee50a4a4ca23bdc49f75ea8242d8a2193b3b", "name": "https://git.kernel.org/stable/c/bc9cee50a4a4ca23bdc49f75ea8242d8a2193b3b", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/c516db6ab9eabbedbc430b4f93b0d8728e9b427f", "name": "https://git.kernel.org/stable/c/c516db6ab9eabbedbc430b4f93b0d8728e9b427f", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/c516db6ab9eabbedbc430b4f93b0d8728e9b427f", "name": "https://git.kernel.org/stable/c/c516db6ab9eabbedbc430b4f93b0d8728e9b427f", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/eb85dace897c5986bc2f36b3c783c6abb8a4292e", "name": "https://git.kernel.org/stable/c/eb85dace897c5986bc2f36b3c783c6abb8a4292e", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/eb85dace897c5986bc2f36b3c783c6abb8a4292e", "name": "https://git.kernel.org/stable/c/eb85dace897c5986bc2f36b3c783c6abb8a4292e", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/eff7cdf890b02596b8d73e910bdbdd489175dbdb", "name": "https://git.kernel.org/stable/c/eff7cdf890b02596b8d73e910bdbdd489175dbdb", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/eff7cdf890b02596b8d73e910bdbdd489175dbdb", "name": "https://git.kernel.org/stable/c/eff7cdf890b02596b8d73e910bdbdd489175dbdb", "refsource": "", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nnilfs2: fix potential hang in nilfs_detach_log_writer()\n\nSyzbot has reported a potential hang in nilfs_detach_log_writer() called\nduring nilfs2 unmount.\n\nAnalysis revealed that this is because nilfs_segctor_sync(), which\nsynchronizes with the log writer thread, can be called after\nnilfs_segctor_destroy() terminates that thread, as shown in the call trace\nbelow:\n\nnilfs_detach_log_writer\n  nilfs_segctor_destroy\n    nilfs_segctor_kill_thread  --> Shut down log writer thread\n    flush_work\n      nilfs_iput_work_func\n        nilfs_dispose_list\n          iput\n            nilfs_evict_inode\n              nilfs_transaction_commit\n                nilfs_construct_segment (if inode needs sync)\n                  nilfs_segctor_sync  --> Attempt to synchronize with\n                                          log writer thread\n                           *** DEADLOCK ***\n\nFix this issue by changing nilfs_segctor_sync() so that the log writer\nthread returns normally without synchronizing after it terminates, and by\nforcing tasks that are already waiting to complete once after the thread\nterminates.\n\nThe skipped inode metadata flushout will then be processed together in the\nsubsequent cleanup work in nilfs_segctor_destroy()."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}, "impact": {}, "publishedDate": "2024-06-19T14:15Z", "lastModifiedDate": "2024-11-21T09:26Z"}