{"publishedDate": "2024-11-22T20:15Z", "lastModifiedDate": "2025-09-15T18:03Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2024-53253", "ASSIGNER": "security-advisories@github.com"}, "description": {"description_data": [{"lang": "en", "value": "Sentry is an error tracking and performance monitoring platform. Version 24.11.0, and only version 24.11.0, is vulnerable to a scenario where a specific error message generated by the Sentry platform could include a plaintext Client ID and Client Secret for an application integration. The Client ID and Client Secret would not be displayed in the UI, but would be returned in the underlying HTTP response to the end user. This could occur under the following conditions: An app installation made use of a Search UI component with the `async` flag set to true (default: true); auser types types into the Search Component which creates a request to the third-party for search or query results; and that third-party response may then fail validation and Sentry would return the `select-requester.invalid-response` error code along with a serialized version of a Sentry application containing the integration Client Secret. Should this error be found, it's reasonable to assume the potential exposure of an integration Client Secret. However, an ID and Secret pair alone does not provide direct access to any data. For that secret to be abused an attacker would also need to obtain a valid API token for a Sentry application. \n\nSentry SaaS users do not need to take any action. For Sentry SaaS users, only a single application integration was impacted and the owner has rotated their Client Secret. No abuse of the leaked Client Secret has occurred.\n\nAs of time of publication, a fix is available for users of Sentry self-hosted in pull request 81038. Sentry self-hosted does not ship with any application integrations. This could only impact self-hosted users that maintain their own integrations. In that case, search for a `select-requester.invalid-response` event. Please note that this error was also shared with another event unrelated to this advisory so Sentry self-hosted users will also need to review the parameters logged for each named event. Sentry self-hosted users may review `select_requester.py` for the instances where these errors can be generated. With the security fix this is no longer a shared event type. Sentry self-hosted users may not install version 24.11.0 and instead wait for the next release. Self-hosted instance that are already running the affected version may consider downgrading to to 24.10.0."}, {"lang": "es", "value": "Sentry es una plataforma de seguimiento de errores y monitoreo de rendimiento. La versi\u00f3n 24.11.0, y solo la versi\u00f3n 24.11.0, es vulnerable a un escenario en el que un mensaje de error espec\u00edfico generado por la plataforma Sentry podr\u00eda incluir un ID de cliente y un secreto de cliente en texto plano para una integraci\u00f3n de aplicaciones. El ID de cliente y el secreto de cliente no se mostrar\u00edan en la interfaz de usuario, pero se devolver\u00edan en la respuesta HTTP subyacente al usuario final. Esto podr\u00eda ocurrir en las siguientes condiciones: una instalaci\u00f3n de aplicaci\u00f3n hizo uso de un componente de interfaz de usuario de b\u00fasqueda con el indicador `async` establecido en verdadero (valor predeterminado: verdadero); un usuario escribe en el componente de b\u00fasqueda que crea una solicitud al tercero para obtener resultados de b\u00fasqueda o consulta; y esa respuesta de terceros puede fallar en la validaci\u00f3n y Sentry devolver\u00eda el c\u00f3digo de error `select-requester.invalid-response` junto con una versi\u00f3n serializada de una aplicaci\u00f3n Sentry que contiene el secreto de cliente de integraci\u00f3n. Si se encuentra este error, es razonable suponer la posible exposici\u00f3n de un secreto de cliente de integraci\u00f3n. Sin embargo, un par de ID y secreto por s\u00ed solo no proporciona acceso directo a ning\u00fan dato. Para que se abuse de ese secreto, un atacante tambi\u00e9n necesitar\u00eda obtener un token de API v\u00e1lido para una aplicaci\u00f3n Sentry. Los usuarios de Sentry SaaS no necesitan realizar ninguna acci\u00f3n. Para los usuarios de Sentry SaaS, solo se vio afectada una \u00fanica integraci\u00f3n de aplicaci\u00f3n y el propietario ha rotado su secreto de cliente. No se ha producido ning\u00fan abuso del secreto de cliente filtrado. Al momento de la publicaci\u00f3n, hay una soluci\u00f3n disponible para los usuarios de Sentry autoalojado en la solicitud de extracci\u00f3n 81038. Sentry autoalojado no se env\u00eda con ninguna integraci\u00f3n de aplicaciones. Esto solo podr\u00eda afectar a los usuarios autoalojados que mantienen sus propias integraciones. En ese caso, busque un evento `select-requester.invalid-response`. Tenga en cuenta que este error tambi\u00e9n se comparti\u00f3 con otro evento no relacionado con este aviso, por lo que los usuarios autoalojados de Sentry tambi\u00e9n deber\u00e1n revisar los par\u00e1metros registrados para cada evento nombrado. Los usuarios autoalojados de Sentry pueden revisar `select_requester.py` para las instancias en las que se pueden generar estos errores. Con la soluci\u00f3n de seguridad, este ya no es un tipo de evento compartido. Los usuarios alojados en Sentry no pueden instalar la versi\u00f3n 24.11.0 y, en su lugar, esperar a la pr\u00f3xima versi\u00f3n. Las instancias alojadas en Sentry que ya est\u00e9n ejecutando la versi\u00f3n afectada pueden considerar la posibilidad de actualizar a la versi\u00f3n 24.10.0."}]}, "references": {"reference_data": [{"url": "https://github.com/getsentry/sentry/pull/79377", "name": "", "refsource": "", "tags": ["Issue Tracking"]}, {"url": "https://github.com/getsentry/sentry/pull/81038", "name": "", "refsource": "", "tags": ["Issue Tracking"]}, {"url": "https://github.com/getsentry/sentry/security/advisories/GHSA-v5h2-q2w4-gpcx", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-209"}]}]}}, "impact": {"baseMetricV3": {"exploitabilityScore": 3.9, "impactScore": 1.4, "cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "baseScore": 5.3, "baseSeverity": "MEDIUM", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "LOW", "integrityImpact": "NONE", "availabilityImpact": "NONE"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "negate": false, "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:sentry:sentry:24.11.0:*:*:*:*:*:*:*", "matchCriteriaId": "BD9BC012-BE1B-467F-9D9F-BBC0446EE702", "cpe_name": []}]}]}}