{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2024-21543", "ASSIGNER": "report@snyk.io"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://github.com/sunscrapers/djoser/commit/d33c3993c0c735f23cbedc60fa59fce69354f19d", "name": "https://github.com/sunscrapers/djoser/commit/d33c3993c0c735f23cbedc60fa59fce69354f19d", "refsource": "", "tags": []}, {"url": "https://github.com/sunscrapers/djoser/issues/795", "name": "https://github.com/sunscrapers/djoser/issues/795", "refsource": "", "tags": []}, {"url": "https://github.com/sunscrapers/djoser/pull/819", "name": "https://github.com/sunscrapers/djoser/pull/819", "refsource": "", "tags": []}, {"url": "https://github.com/sunscrapers/djoser/releases/tag/2.3.0", "name": "https://github.com/sunscrapers/djoser/releases/tag/2.3.0", "refsource": "", "tags": []}, {"url": "https://security.snyk.io/vuln/SNYK-PYTHON-DJOSER-8366540", "name": "https://security.snyk.io/vuln/SNYK-PYTHON-DJOSER-8366540", "refsource": "", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "Versions of the package djoser before 2.3.0 are vulnerable to Authentication Bypass when the authenticate() function fails. This is because the system falls back to querying the database directly, granting access to users with valid credentials, and eventually bypassing custom authentication checks such as two-factor authentication, LDAP validations, or requirements from configured AUTHENTICATION_BACKENDS."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}, "impact": {}, "publishedDate": "2024-12-13T05:15Z", "lastModifiedDate": "2024-12-13T20:15Z"}