{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2024-39614", "ASSIGNER": "cve@mitre.org"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://docs.djangoproject.com/en/dev/releases/security/", "name": "https://docs.djangoproject.com/en/dev/releases/security/", "refsource": "", "tags": []}, {"url": "https://docs.djangoproject.com/en/dev/releases/security/", "name": "https://docs.djangoproject.com/en/dev/releases/security/", "refsource": "", "tags": []}, {"url": "https://groups.google.com/forum/#%21forum/django-announce", "name": "https://groups.google.com/forum/#%21forum/django-announce", "refsource": "", "tags": []}, {"url": "https://groups.google.com/forum/#%21forum/django-announce", "name": "https://groups.google.com/forum/#%21forum/django-announce", "refsource": "", "tags": []}, {"url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/", "name": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/", "refsource": "", "tags": []}, {"url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/", "name": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/", "refsource": "", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}, "impact": {}, "publishedDate": "2024-07-10T05:15Z", "lastModifiedDate": "2024-11-21T09:28Z"}