{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2024-0654", "ASSIGNER": "cna@vuldb.com"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://github.com/bayuncao/vul-cve-4", "name": "https://github.com/bayuncao/vul-cve-4", "refsource": "", "tags": ["Broken Link"]}, {"url": "https://github.com/bayuncao/vul-cve-4", "name": "https://github.com/bayuncao/vul-cve-4", "refsource": "", "tags": ["Broken Link"]}, {"url": "https://github.com/bayuncao/vul-cve-4/blob/main/picture/1071705290840_.pic_hd.jpg", "name": "https://github.com/bayuncao/vul-cve-4/blob/main/picture/1071705290840_.pic_hd.jpg", "refsource": "", "tags": ["Broken Link"]}, {"url": "https://github.com/bayuncao/vul-cve-4/blob/main/picture/1071705290840_.pic_hd.jpg", "name": "https://github.com/bayuncao/vul-cve-4/blob/main/picture/1071705290840_.pic_hd.jpg", "refsource": "", "tags": ["Broken Link"]}, {"url": "https://vuldb.com/?ctiid.251382", "name": "https://vuldb.com/?ctiid.251382", "refsource": "", "tags": ["Permissions Required", "Third Party Advisory"]}, {"url": "https://vuldb.com/?ctiid.251382", "name": "https://vuldb.com/?ctiid.251382", "refsource": "", "tags": ["Permissions Required", "Third Party Advisory"]}, {"url": "https://vuldb.com/?id.251382", "name": "https://vuldb.com/?id.251382", "refsource": "", "tags": ["Permissions Required", "Third Party Advisory"]}, {"url": "https://vuldb.com/?id.251382", "name": "https://vuldb.com/?id.251382", "refsource": "", "tags": ["Permissions Required", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "A vulnerability, which was classified as problematic, was found in DeepFaceLab pretrained DF.wf.288res.384.92.72.22. Affected is an unknown function of the file mainscripts/Util.py. The manipulation leads to deserialization. Local access is required to approach this attack. The exploit has been disclosed to the public and may be used. VDB-251382 is the identifier assigned to this vulnerability."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:iperov:deepfacelab:df.wf.288res.384.92.72.22:*:*:*:*:*:*:*", "cpe_name": []}]}]}, "impact": {"baseMetricV3": {"cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H", "attackVector": "LOCAL", "attackComplexity": "LOW", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "HIGH", "baseScore": 7.8, "baseSeverity": "HIGH"}, "exploitabilityScore": 1.8, "impactScore": 5.9}}, "publishedDate": "2024-01-18T01:15Z", "lastModifiedDate": "2024-11-21T08:47Z"}