{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2024-26689", "ASSIGNER": "cve@kernel.org"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://git.kernel.org/stable/c/70e329b440762390258a6fe8c0de93c9fdd56c77", "name": "https://git.kernel.org/stable/c/70e329b440762390258a6fe8c0de93c9fdd56c77", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/70e329b440762390258a6fe8c0de93c9fdd56c77", "name": "https://git.kernel.org/stable/c/70e329b440762390258a6fe8c0de93c9fdd56c77", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/7958c1bf5b03c6f1f58e724dbdec93f8f60b96fc", "name": "https://git.kernel.org/stable/c/7958c1bf5b03c6f1f58e724dbdec93f8f60b96fc", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/7958c1bf5b03c6f1f58e724dbdec93f8f60b96fc", "name": "https://git.kernel.org/stable/c/7958c1bf5b03c6f1f58e724dbdec93f8f60b96fc", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/8180d0c27b93a6eb60da1b08ea079e3926328214", "name": "https://git.kernel.org/stable/c/8180d0c27b93a6eb60da1b08ea079e3926328214", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/8180d0c27b93a6eb60da1b08ea079e3926328214", "name": "https://git.kernel.org/stable/c/8180d0c27b93a6eb60da1b08ea079e3926328214", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/ae20db45e482303a20e56f2db667a9d9c54ac7e7", "name": "https://git.kernel.org/stable/c/ae20db45e482303a20e56f2db667a9d9c54ac7e7", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/ae20db45e482303a20e56f2db667a9d9c54ac7e7", "name": "https://git.kernel.org/stable/c/ae20db45e482303a20e56f2db667a9d9c54ac7e7", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/cda4672da1c26835dcbd7aec2bfed954eda9b5ef", "name": "https://git.kernel.org/stable/c/cda4672da1c26835dcbd7aec2bfed954eda9b5ef", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/cda4672da1c26835dcbd7aec2bfed954eda9b5ef", "name": "https://git.kernel.org/stable/c/cda4672da1c26835dcbd7aec2bfed954eda9b5ef", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/f3f98d7d84b31828004545e29fd7262b9f444139", "name": "https://git.kernel.org/stable/c/f3f98d7d84b31828004545e29fd7262b9f444139", "refsource": "", "tags": []}, {"url": "https://git.kernel.org/stable/c/f3f98d7d84b31828004545e29fd7262b9f444139", "name": "https://git.kernel.org/stable/c/f3f98d7d84b31828004545e29fd7262b9f444139", "refsource": "", "tags": []}, {"url": "https://lists.debian.org/debian-lts-announce/2024/06/msg00017.html", "name": "https://lists.debian.org/debian-lts-announce/2024/06/msg00017.html", "refsource": "", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nceph: prevent use-after-free in encode_cap_msg()\n\nIn fs/ceph/caps.c, in encode_cap_msg(), \"use after free\" error was\ncaught by KASAN at this line - 'ceph_buffer_get(arg->xattr_buf);'. This\nimplies before the refcount could be increment here, it was freed.\n\nIn same file, in \"handle_cap_grant()\" refcount is decremented by this\nline - 'ceph_buffer_put(ci->i_xattrs.blob);'. It appears that a race\noccurred and resource was freed by the latter line before the former\nline could increment it.\n\nencode_cap_msg() is called by __send_cap() and __send_cap() is called by\nceph_check_caps() after calling __prep_cap(). __prep_cap() is where\narg->xattr_buf is assigned to ci->i_xattrs.blob. This is the spot where\nthe refcount must be increased to prevent \"use after free\" error."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}, "impact": {}, "publishedDate": "2024-04-03T15:15Z", "lastModifiedDate": "2024-11-21T09:02Z"}