{"publishedDate": "2023-03-26T19:15Z", "lastModifiedDate": "2024-11-21T07:56Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2023-28859", "ASSIGNER": "cve@mitre.org"}, "description": {"description_data": [{"lang": "en", "value": "redis-py before 4.4.4 and 4.5.x before 4.5.4 leaves a connection open after canceling an async Redis command at an inopportune time, and can send response data to the client of an unrelated request. (This could, for example, happen for a non-pipeline operation.) NOTE: the solutions for CVE-2023-28859 address data leakage across AsyncIO connections in general."}]}, "references": {"reference_data": [{"url": "https://github.com/redis/redis-py/issues/2665", "name": "", "refsource": "", "tags": ["Issue Tracking", "Patch", "Vendor Advisory"]}, {"url": "https://github.com/redis/redis-py/pull/2641", "name": "", "refsource": "", "tags": ["Issue Tracking", "Patch"]}, {"url": "https://github.com/redis/redis-py/pull/2666", "name": "", "refsource": "", "tags": ["Release Notes"]}, {"url": "https://github.com/redis/redis-py/releases/tag/v4.4.4", "name": "", "refsource": "", "tags": ["Release Notes"]}, {"url": "https://github.com/redis/redis-py/releases/tag/v4.5.4", "name": "", "refsource": "", "tags": ["Release Notes"]}, {"url": "https://github.com/redis/redis-py/issues/2665", "name": "", "refsource": "", "tags": ["Issue Tracking", "Patch", "Vendor Advisory"]}, {"url": "https://github.com/redis/redis-py/pull/2641", "name": "", "refsource": "", "tags": ["Issue Tracking", "Patch"]}, {"url": "https://github.com/redis/redis-py/pull/2666", "name": "", "refsource": "", "tags": ["Release Notes"]}, {"url": "https://github.com/redis/redis-py/releases/tag/v4.4.4", "name": "", "refsource": "", "tags": ["Release Notes"]}, {"url": "https://github.com/redis/redis-py/releases/tag/v4.5.4", "name": "", "refsource": "", "tags": ["Release Notes"]}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-459"}]}]}}, "impact": {"baseMetricV3": {"exploitabilityScore": 2.8, "impactScore": 3.6, "cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N", "baseScore": 6.5, "baseSeverity": "MEDIUM", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "NONE", "availabilityImpact": "NONE"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "negate": false, "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:redis:redis-py:*:*:*:*:*:*:*:*", "matchCriteriaId": "8BF5D290-49BC-4C70-B801-9DCE97070663", "cpe_name": [], "versionStartIncluding": "4.2.0", "versionEndExcluding": "4.4.4"}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:redis:redis-py:*:*:*:*:*:*:*:*", "matchCriteriaId": "39E01CD5-9AC0-46ED-A952-1EAD9FBFC930", "cpe_name": [], "versionStartIncluding": "4.5.0", "versionEndExcluding": "4.5.4"}]}]}}