{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2022-45199", "ASSIGNER": "cve@mitre.org"}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-400"}]}]}, "references": {"reference_data": [{"url": "https://bugs.gentoo.org/878769", "name": "https://bugs.gentoo.org/878769", "refsource": "", "tags": ["Issue Tracking", "Patch", "Third Party Advisory"]}, {"url": "https://bugs.gentoo.org/878769", "name": "https://bugs.gentoo.org/878769", "refsource": "", "tags": ["Issue Tracking", "Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/commit/2444cddab2f83f28687c7c20871574acbb6dbcf3", "name": "https://github.com/python-pillow/Pillow/commit/2444cddab2f83f28687c7c20871574acbb6dbcf3", "refsource": "", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/commit/2444cddab2f83f28687c7c20871574acbb6dbcf3", "name": "https://github.com/python-pillow/Pillow/commit/2444cddab2f83f28687c7c20871574acbb6dbcf3", "refsource": "", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/pull/6700", "name": "https://github.com/python-pillow/Pillow/pull/6700", "refsource": "", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/pull/6700", "name": "https://github.com/python-pillow/Pillow/pull/6700", "refsource": "", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/releases/tag/9.3.0", "name": "https://github.com/python-pillow/Pillow/releases/tag/9.3.0", "refsource": "", "tags": ["Release Notes", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/releases/tag/9.3.0", "name": "https://github.com/python-pillow/Pillow/releases/tag/9.3.0", "refsource": "", "tags": ["Release Notes", "Third Party Advisory"]}, {"url": "https://security.gentoo.org/glsa/202211-10", "name": "GLSA-202211-10", "refsource": "", "tags": ["Third Party Advisory"]}, {"url": "https://security.gentoo.org/glsa/202211-10", "name": "GLSA-202211-10", "refsource": "", "tags": ["Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "Pillow before 9.3.0 allows denial of service via SAMPLESPERPIXEL."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:python:pillow:*:*:*:*:*:*:*:*", "versionEndExcluding": "9.3.0", "cpe_name": []}]}]}, "impact": {"baseMetricV3": {"cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH", "baseScore": 7.5, "baseSeverity": "HIGH"}, "exploitabilityScore": 3.9, "impactScore": 3.6}}, "publishedDate": "2022-11-14T07:15Z", "lastModifiedDate": "2024-11-21T07:28Z"}